package se.je.trainee_project.Model;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.math.BigInteger;

/* This class is the result of using xjc through the command line tool to read the ChasTraineeXSD.xsd file and
   compiling the schema to the classes available in the Model package.

   For a better object oriented approach and for easier visibility over the different classes, I used the file
   binding.xml to generate three different classes ones instead of one nested class.

   I've also removed some of the autogenerated methods I did not need and removed some the autogenerated comments
   in the Item, ShipOrder and ShipTo classes.
*/


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "title",
        "note",
        "quantity",
        "price"
})

public class Item {

    // Declaring variables with the annotations defined in the XSD file
    @XmlElement(required = true)
    protected String title;
    protected String note;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger quantity;
    @XmlElement(required = true)
    protected BigDecimal price;

    // Getters and Setters for the declared variables.
    public void setTitle(String title) {
        this.title = title;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public void setQuantity(BigInteger quantity) {
        this.quantity = quantity;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    // Override method for a better looking console print out when unmarshalling shipOrderModified.xml file.
    @Override
    public String toString() {
        return "Item{" +
                "title='" + title + '\'' +
                ", note='" + note + '\'' +
                ", quantity=" + quantity +
                ", price=" + price +
                '}';
    }
}
