package se.je.trainee_project.Model;

import javax.xml.bind.annotation.*;

/* This class is the result of using xjc through the command line tool to read the ChasTraineeXSD.xsd file and
   compiling the schema to the classes available in the Model package.

   For a better object oriented approach and for easier visibility over the different classes, I used the file
   binding.xml to generate three different classes ones instead of one nested class.

   I've also removed some of the autogenerated methods I did not need and removed some the autogenerated comments
   in the Item, ShipOrder and ShipTo classes.
*/

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "name",
        "address",
        "city",
        "country"
})

public class ShipTo {

    // Declaring variables with the annotations defined in the XSD file
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String address;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String country;

    // Getters and Setters for the declared variables.
    public void setName(String name) {
        this.name = name;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setCountry(String country) {
        this.country = country;
    }
}

