package se.je.trainee_project.Model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/* This class is the result of using xjc through the command line tool to read the ChasTraineeXSD.xsd file and
   compiling the schema to the classes available in the Model package.

   For a better object oriented approach and for easier visibility over the different classes, I used the file
   binding.xml to generate three different classes ones instead of one nested class.

   I've also removed some of the autogenerated methods I did not need and removed some the autogenerated comments
   in the Item, ShipOrder and ShipTo classes.

   I've also renamed some of the variables in this class for better readability. For example changing "orderperson"
   to "orderPerson".
*/

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "orderPerson",
        "shipTo",
        "item"
})

@XmlRootElement(name = "shiporder")
public class ShipOrder {

    // Declaring variables with the annotations defined in the XSD file
    @XmlElement(required = true)
    protected String orderPerson;
    @XmlElement(required = true)
    protected ShipTo shipTo;
    @XmlElement(required = true)
    protected List<Item> item;
    @XmlAttribute(name = "orderid", required = true)
    protected String orderId;

    // Getters and Setters for the declared variables.
    public void setOrderPerson(String orderPerson) {
        this.orderPerson = orderPerson;
    }

    public void setShipTo(ShipTo shipTo) {
        this.shipTo = shipTo;
    }

    public List<Item> getItem() {
        if (item == null) {
            item = new ArrayList<>();
        }
        return this.item;
    }

    // Method to add multiple Item objects to a ShipOrder object
    public void setItem(Item item) {
        this.getItem().add(item);
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
}
