package bestgymever.controller;

public enum AdministratorState {
    START, USERNAME, PASSWORD, MENU,
    CHOOSEROOM, CHOOSETYPE, CHOOSEAVAILABLESLOTS, CHOOSESTARTDATE, CHOOSEENDDATE, CREATEWORKOUT,
    CHOOSEUSERNAME, CHOOSEPASSWORD, CREATEUSER;
}

enum AdministratorCreationState {
    MEMBER, RECEPTIONIST, PERSONALTRAINER;
}

